name: Branch Name
on:
  pull_request:
    types: [opened, reopened, edited]
jobs:
  branch_name:
    runs-on: ubuntu-latest
    name: Branch Name
    steps:
      - uses: AlbertHernandez/branch-name-action@v1.0.2
        with:
          branch_pattern: 'add|update|fix'
          comment_for_invalid_branch_name: 'Ooops! This branch name is not following the standards!'
          fail_if_invalid_branch_name: 'true'
          ignore_branch_pattern: 'master|beta'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

